### ISSUE TITLE
Simple jasmine.yml errors not handled well

### ISSUE THREAD

**Issue by Gerg** [jasmine/jasmine-py#16]
Typing

``` yml
src_files: 'javascripts/counter.js'
```

instead of

``` yml
src_files:
 - 'javascripts/counter.js'
```

Results in config#_glob_filelist getting a string instead of an array, which results in crazytown.

``` html
<script src="__src__/../../../../.." type="text/javascript"></script>
<script src="__src__/." type="text/javascript"></script>  
```

**Comment by slackersoft** [comment]
We'd be happy to review a pull request that either:

1. `raises` an error if the things that are expected to be arrays are not
or
2. Treats a string as an array of one value.

**Comment by sgravrock** [comment]
Closing since jasmine-py is discontinued.
