### ISSUE TITLE
Leading slashes in jasmine.yml should be correctly handled

### ISSUE THREAD

**Issue by Gerg** [jasmine/jasmine-py#19]
```
src_files:
  - 'website/javascripts/**/*.js'

vs

src_files:
  - '/website/javascripts/**/*.js'

```

**Comment by slackersoft** [comment]
We would be happy to review a pull request that treated paths with a leading `/` the same as a path without a leading `/`.

**Comment by sgravrock** [comment]
Closing since jasmine-py is deprecated and we don't intend to add any new features.
