### ISSUE TITLE
jasmine-jquery fixtures

### ISSUE THREAD

**Issue by codingjoe** [jasmine/jasmine-py#23]
Hey I'm having some trouble with `jasmine-jquery` and jasmine-py. The helper works fine, but the fixtures don't at least not the once loading from filesystem.
Does anyone have any experience with that? I'll dig into the code to see why jasmine returns a 404 for the fixtures.
Cheers, joe

**Comment by codingjoe** [comment]
I found a workaround by adding helpers to the `src` files and changing the `fixturesPath` to start with `__src__`
It's not really nice, as the src files are loaded in the head element. I'll write a patch, that allows flask to deliver fixtures.

**Comment by Gerg** [comment]
Hey Joe,
Jasmine jQuery is not owned by the jasmine maintainers, so I'm not sure how it is trying to load these fixtures. If it is trying to request them from your local filesystem, this may just be an issue of cross-origin requests.

**Comment by codingjoe** [comment]
@Gerg no it doesn't but your flask setup currently only delivers 3 `filetypes`.
I could create a patch that will allow using `jasmine-jquery` without changing the `fixturePath`, but that would require changing the current route design. As an alternative I could write a documentation and how to change the `fixturePath`.
I let you be the judge of that, but I prefer the first solution.

**Comment by slackersoft** [comment]
We've recently rejiggered how the files are served, so it should be possible to add a mechanism to mount another engine inside cherrypy to serve other things. http://docs.cherrypy.org/en/latest/basics.html?highlight=mount#multiple-applications

**Comment by slackersoft** [comment]
We haven't heard anything else on this issue in a while and we think some of the newer versions of Jasmine should support mounting other cherrypy engines to serve other file types, so I'm going to close this.

I'd be happy to talk more if we need some extension points to inject a server more easily. Thanks for using Jasmine!
