### ISSUE TITLE
Code coverage tool missing

### ISSUE THREAD

**Issue by MariusBaci** [jasmine/jasmine-py#27]
Is there a way to analyze/add code coverage to this Jasmine Python ? 
Or maybe a way to integrate it with some existing tools (Blanketjs, Istanbul,...) in order to generate some coverage statistics ?
Thanks.

**Comment by Gerg** [comment]
This seems like a good idea. I added a story here: https://www.pivotaltracker.com/story/show/100944886

**Comment by slackersoft** [comment]
Code coverage is a tricky thing and not something we want super tightly integrated with Jasmine. That said, many of the javascript code coverage tools already work with Jasmine and should have examples of how to plug them into your existing setup.

I'm going to close this issue, but we would be happy to review a pull request to [the docs repo](https://github.com/jasmine/jasmine.github.io) to add a tutorial or something on how to integrate one or more coverage tools.

Closing this issue. Thanks for using Jasmine!
