### ISSUE TITLE
support selenium 3

### ISSUE THREAD

**Issue by srittau** [jasmine/jasmine-py#31]
Currently requirements.txt requires selenium < 3. Selenium 3.0.0b2 is the current version on pypi and contains important fixes, but can't be installed in my projects yet, because of the conflict with jasmine.

**Comment by Gerg** [comment]
Selenium 3 does not currently work with jasmine-py, so I can't remove the upper bound. Once they cut a final release, we can update jasmine to use 3.

**Comment by lukeahn** [comment]
They still have DistributionNotFound: selenium>=2.0,<3.0 condition...
