### ISSUE TITLE
chatdet fixed dependency

### ISSUE THREAD

**Issue by gnarvaja** [jasmine/jasmine-py#40]
Currently jasmine-py has a fixed dependency of chatdet library at 2.3 version. I think it's not needed and this creates conflict with recent versions of packages like requests that require chatdet >=3.0.2.

Proposed fix (in requirements.txt):

`-chardet==2.3`
`+chardet`

Sorry I don't have now enough time to make the PR.

**Comment by slackersoft** [comment]
I think we ultimately want to fix this by using something like `sendfile` instead of reading the entire file into memory to check it's character set. This would also fix #35 in the process as well.
