### ISSUE TITLE
jasmine-ci doesn't execute tests

### ISSUE THREAD

**Issue by moshemeirelles** [jasmine/jasmine-py#41]
I'm having trouble to execute jasmine-ci, using Python 3.5.1.

Running `jasmine-ci --browser phantomjs` it doesn't execute my test suite , returning `0 specs, 0 failed`; at the point that running it on browser using `jasmine` command shows me `21 specs, 0 failures`.

I tried to find this issue and can't find any other with this trouble.

**Comment by slackersoft** [comment]
Hmm, what version of phantom are you using? We also just reworked some internals so that Jasmine-Py should be able to use Selenium 3 going forward. This should be out in the next release.

**Comment by slackersoft** [comment]
Update: 2.7.0 is out with support for selenium 3 and a bunch of other fixes.

**Comment by mshmeirelles** [comment]
Hello @slackersoft , sorry for late answer. I've been traveling last days. We were using 2.6.0, Upgrading solved our problem. Thank you a lot for your attention!
