### ISSUE TITLE
Jasmine files not served with correct content type

### ISSUE THREAD

**Issue by wuzuf** [jasmine/jasmine-py#42]
Hi,

Since jasmine-py 2.6.0 (I believe, at least 2.5.0 was working), when I point my browser to http://localhost:8888/ with chrome, display is completely screwed up. After investigation, I believe this is linked to the jasmine_core files not being served with the correct content type. Apparently firefox is more permissive and guessing the type, hence it did not show up in your test cases.
I will submit a PR to fix this.

Gabriel

**Comment by FelixSchwarz** [comment]
I'm seeing the problem also with Firefox 55 (Linux). Before I found your pull request I hacked up something similar so I can attest your diagnosis is correct.
