### ISSUE TITLE
With Jasmine 3.0, current documentation inaccurate 

### ISSUE THREAD

**Issue by aschokking** [jasmine/jasmine-py#46]
Installed the latest jasmine 3.0+ via pip and commands prescribed in the docs like `jasmine-install` aren't there. Rolled back to 2.9.0 and things worked as described.

**Comment by slackersoft** [comment]
Oops, you're right. We collapsed the interface down for Jasmine 3.0 so only one executable is published with subcommands. The docs should be updated now.

Thanks for using Jasmine!

**Comment by aschokking** [comment]
Thank you! Could you also update the readme in the github repo? https://github.com/jasmine/jasmine-py/blob/master/README.md
