### ISSUE TITLE
No MySQL support MySQL support does not seem to be installed on this server

### ISSUE THREAD

**Issue by rhuancampos** [jasmine/jasmine-py#47]
Hello, I am trying to implement JASMINE on a linux server (ubuntu), however it presents these messages in its web panel, after performing the settings. And php-mysql is already installed, but the message still persists.

> "No MySQL support MySQL support does not seem to be installed on this server
> Check that the MySQL support for PHP is installed: It is usually a package called something like "php-mysql" on GNU/Linux distribs.Do not forget to restart your web server if needed."

**Comment by slackersoft** [comment]
Jasmine is a JavaScript testing framework, and as such doesn't know anything about MySQL (or any other database). Are you sure you're making an issue on the correct project?

**Comment by rhuancampos** [comment]
I'm not using the install mode that is in Git, I'm using this alternate mode, which by backend in Py. This mode of installation is https://itbr.org/phpbb3/viewtopic.php?t=835

**Comment by slackersoft** [comment]
I think you might be looking for https://github.com/eduardoweiland/jasmine which is an SNMP library, and appears to use MySQL in some form.

This repository is for a JavaScript testing framework and does not have a server component that needs any kind of database.

Closing.
